### PR TITLE
fix(Search): defaultValue prop support

### LINKED ISSUE #56: Search component doesn't support defaultValue prop
screen shot 2017-06-21 at 2 20 16 pm
screen shot 2017-06-21 at 11 36 05 am

### PR DESCRIPTION
**Pull request by ritch**
- use the input directly instead of storing value as state
 - fix `defaultValue` prop

This should fix #56 and #30

### CODE REVIEW

File: components/Search.js [hunk 1]
```diff
@@ -24,23 +24,14 @@ class Search extends Component {
...
-    hasContent: false,
   };
 
   toggleClearIcon = evt => {
-    const hasContent = evt.target.value.length > 0;
-    this.setState({
-      hasContent,
-      value: evt.target.value,
-    });
+    this.input.value = evt.target.value;
```
Comment (marijohannessen) [inline components/Search.js]: Do you think we could also add a `this.props.onInput()` call here? That way you can trigger more stuff on input instead of just clearing the icon (implementing a search on carbondesignsystem.com right now, and found that I needed this).

Comment (ritch) [inline components/Search.js]: Once this PR is merged you can trigger things when the value of the `input` using the `onChange` prop which will be passed to `input`.

```jsx
<Search onChange={e => console.log(e.value) } />
```

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832") to [Bluemix Design System](https://console.bluemix.net/apps/1a30065f-cef2-4933-ba3f-3ff6669a0abd?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 33752d8143d63b5e45fb2d631f39bf9d4448b00c
