### PR TITLE
fix(DataTable): removed hardcoded id, resolves #735

### LINKED ISSUE #735: Remove Hardcoded id in TableToolbarSearch
## Detailed description

This is a bug in the component itself. Having the id hardcoded is causing 'non-unique id' errors.
This issue appears to have been fixed in the Search component but not in the TableToolbarSearch (for reference) 

## Additional information
screen shot 2018-03-20 at 7 55 27 pm

### PR DESCRIPTION
**Pull request by bellsworth13**
Fixes #735 

**New**

TableToolBarSearch can be passed id prop

**Removed**

Hardcoded Id

### CODE REVIEW

File: src/components/DataTable/TableToolbarSearch.js [hunk 1]
```diff
@@ -34,6 +35,7 @@ TableToolbarSearch.propTypes = {
   /**
    * Provide an optional class name for the search container
    */
+  id: PropTypes.string,
```
Comment (asudoh) [inline src/components/DataTable/TableToolbarSearch.js]: Please add a comment for the new `id` prop here so that the prop definitions and the comments are in sync.

Comment (joshblack) [reply src/components/DataTable/TableToolbarSearch.js]: Also, is this a prop type definition that needs to be required, or are we providing a fallback value?

**Comment by joshblack** [comment]
Thanks for working on this @bellsworth13!

**Comment by joshblack** [comment]
cc @asudoh to re-review 🙂
