### PR TITLE
fix(OverflowMenu): clobber DOM for closed overflow menu

### LINKED ISSUE #420: [OverflowMenu]: Menu always in DOM even when not open
## Detailed description

The OverflowMenu always puts the menu in the DOM even when the menu is closed.  This is true for both normal and floating menu.  This causes performance issues when OverflowMenu is used multiple times.

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

The menu should only be put in the DOM when the open.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components 8.1.8
carbon-components-react 4.2.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Watson Conversation

## Steps to reproduce the issue

1. Use an OverflowMenu
2. Use the browser debugger to inspect the DOM, and notice that the menu is always there

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #420. Wanted to see if this kind of change makes sense.

#### Changelog

**Changed**

With this change, the DOM for overflow menu is not rendered until it's open.

### CODE REVIEW

File: src/components/OverflowMenu/OverflowMenu.js [hunk 1]
```diff
@@ -164,7 +166,7 @@ export default class OverflowMenu extends Component {
             description={iconDescription}
             style={{ width: '100%' }}
           />
-          {floatingMenu ? (
+          {!open ? null : floatingMenu ? (
```
Comment (joshblack) [inline src/components/OverflowMenu/OverflowMenu.js]: Could we extract the ternary logic into a function for readability?

Comment (marijohannessen) [reply src/components/OverflowMenu/OverflowMenu.js]: Ooops just realized I merged this before this comment was addressed 😢 I can revert it if you want?!

Comment (asudoh) [reply src/components/OverflowMenu/OverflowMenu.js]: No worries @marijohannessen! 🙂

@joshblack Thank you for giving it a thought, did some clean-up there: https://github.com/carbon-design-system/carbon-components-react/pull/465
