### PR TITLE
fix(NumberInput): pass the evt and dir to events

### LINKED ISSUE #369: NumerInput no longer passes the event param
I've been using `NumberInput` in various ways (shown below) and I've had access to the event object passed by the `onChange` prop. However with the newest version (4.2.2), the param is now `undefined`. v4.2.2 includes the following PR: https://github.com/carbon-design-system/carbon-components-react/pull/362 which looks like it directly affects `NumberInput` code. 
Just for testing, I rolled back to 4.2.1 and the event param is properly being assigned and I'm able to use it as such.

Example code of how I've been using `NumberInput`

```javascript
<NumberInput
  ...
  onChange={this.updateQuantity}
  ...
/>

// or

<NumberInput
  ...
  onChange={(e) => this.updateQuantity(e)}
  ...
/>
```

### PR DESCRIPTION
**Pull request by eddiemonge**
onChange and onClick will now receive the events used to trigger them.
This is a regression fix.

They will also receive the direction as a second argument if the arrows
are used.

Fixes the tests as they were returning false positives when checking on
spies. The spies were not reset between test runs so passing it in one
test means it passed in the rest.

Fixes #369

### CODE REVIEW

File: src/components/NumberInput/NumberInput-test.js [hunk 1]
```diff
@@ -178,22 +178,31 @@ describe('NumberInput', () => {
...
-      const upArrow = wrapper.find('Icon.up-icon').closest('button');
-      const downArrow = wrapper.find('Icon.down-icon').closest('button');
+      let onClick;
+      let onChange;
+      let input;
+      let upArrow;
+      let downArrow;
+      let wrapper;
+
+      beforeEach(() => {
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput-test.js]: reset the state between tests instead of using a shared state

File: src/components/NumberInput/NumberInput-test.js [hunk 2]
```diff
@@ -203,18 +212,21 @@ describe('NumberInput', () => {
       it('should invoke onClick when up arrow is clicked', () => {
         upArrow.simulate('click');
         expect(onClick).toBeCalled();
+        expect(onClick).toHaveBeenCalledWith(expect.anything(), 'up');
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput-test.js]: wasn't sure how to create a synthetic event to pass to expect so `.anything()` matches anything that is not undefined or null. It was called with undefined before

File: src/components/NumberInput/NumberInput-test.js [hunk 3]
```diff
@@ -237,14 +249,22 @@ describe('NumberInput', () => {
         expect(wrapper.state().value).toEqual(90);
       });
 
-      it('should invoke onClick when down arrow is clicked', () => {
+      it('should not invoke onClick when down arrow is clicked and value is 0', () => {
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput-test.js]: this was a false positive in the tests before because value wasn't 0. Resetting in between tests exposed this test's weakness

File: src/components/NumberInput/NumberInput.js [hunk 4]
```diff
@@ -53,7 +53,7 @@ export default class NumberInput extends Component {
         {
           value: evt.target.value,
         },
-        evt => {
+        () => {
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput.js]: having `evt` here was overriding the `evt` passed to the function. The callback to setState doesn't pass anything so evt became undefined
