### PR TITLE
fix(MultiSelect):  close MultiSelect after any option is selected/unselected

### LINKED ISSUE #1009: The top-right of the MultiSelect component doesn't seem to close the box
## Detailed description

There is small dropdown arrow on MultiSelect component. It seems to open/close the MultiSelect component before any option is selected/unselected. 

After clicking inside dropdown to select an option, the top-right button seems to stop working. Clicking on that button while drop-down is closed will not close the box. 

## Steps to reproduce the issue

1. Go to `http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel`
2. Open/close the MultiSelect component by clicking on top-right button.
3. Open the component and select any option from MultiSelect. 
4. Clicking on top-right button doesn't close the box. To close the box one must click outside the MultiSelect component.

### PR DESCRIPTION
**Pull request by rezak-otmani**
Closes  #1009

The Downshift does not close the menu as long as it contains active elements that have not lost the fucus.

Using the code  useed for the `FilterableMultiSelect` component to resolves this problem

#### Changelog

**New**

**Changed**

**Removed**

### CODE REVIEW

**Comment by rezak-otmani** [comment]
Hi @tw15egan, I removed the  function `handleOnToggleMenu()` , since it will not be used now

File: src/components/MultiSelect/MultiSelect.js [hunk 1]
```diff
@@ -119,7 +113,19 @@ export default class MultiSelect extends React.Component {
       // Reference: https://github.com/paypal/downshift/issues/206
       case Downshift.stateChangeTypes.clickButton:
       case Downshift.stateChangeTypes.keyDownSpaceButton:
-        this.handleOnToggleMenu();
+        this.setState(() => {
+          let nextIsOpen = changes.isOpen;
+          if (changes.isOpen === false) {
```
Comment (werne2j) [inline src/components/MultiSelect/MultiSelect.js]: @rezak-otmani instead of doing multiple if-statements, you can combine them into 
```
if (changes.isOpen === false && this.inputNode === document.activeElement) {
  nextIsOpen = true;
}
```

Comment (rezak-otmani) [reply src/components/MultiSelect/MultiSelect.js]: Hi @werne2j  thank's for your review, preference to leave the structure of the code as it is, and keep the comments as they are important so that this piece of code be clear.

Comment (asudoh) [reply src/components/MultiSelect/MultiSelect.js]: While I see there are some cases that nested `if` approach makes the code more clear, I’d avoid using it as the general pattern.
