### PR TITLE
fix(Pagination/Slider): fix unknownProp warnings

### LINKED ISSUE #179: unknownProp warnings
There are a couple of warnings as shown https://travis-ci.org/carbon-design-system/carbon-components-react#L758 

```
    console.error node_modules/fbjs/lib/warning.js:35
      Warning: Unknown prop `stepMuliplier` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
          in div (created by Slider)
          in div (created by Slider)
          in div (created by Slider)
          in Slider (created by WrapperComponent)
          in WrapperComponent
```

### PR DESCRIPTION
**Pull request by eddiemonge**
The props were being passed on the HTML elements which did not support
those attributes

Fixes #179

### CODE REVIEW

File: components/Pagination.js [hunk 1]
```diff
@@ -112,7 +113,7 @@ class Pagination extends Component {
       ...other
     } = this.props;
 
-    const { page, pageSize } = this.state;
+    const { sPage, sPageSize } = this.state;
```
Comment (hellobrian) [inline components/Pagination.js]: Was it with this line that made the prop and state naming confusing? 
Instead of renaming our `state` keys, I would prefer that we reference state within this `render()` method as `this.state.page` or `this.state.pageSize`

cc: @iangfleming @tw15egan @chrisdhanaraj @marijohannessen

Comment (tw15egan) [inline components/Pagination.js]: I agree

File: components/Pagination.js [hunk 2]
```diff
@@ -112,7 +113,8 @@ class Pagination extends Component {
       ...other
     } = this.props;
 
-    const { page, pageSize } = this.state;
+    const statePage = this.state.page;
+    const statePageSize = this.state.pageSize;
```
Comment (hellobrian) [inline components/Pagination.js]: Is there a reason for setting these variables? Why can't you just say `this.state.page` when you need it. 

```js
const statePage = this.state.page;
const statePageSize = this.state.pageSize;
```

Comment (eddiemonge) [inline components/Pagination.js]: Yes. One object lookup is more performant than a lot of them

Comment (hellobrian) [inline components/Pagination.js]: 👍

**Comment by chrisdhanaraj** [comment]
👍  @eddiemonge - good to go once merge conflicts resolved

**Comment by eddiemonge** [comment]
Updated

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 241a15e00daa60858cdab9a440d23eb24fa473a0
