### PR TITLE
fix ComposedModal does not close when open, resolves #738

### LINKED ISSUE #738: ComposedModal does not close when open
@bellsworth13 reported an issue in CloudFoundry where the ComposedModal doesn't close when expected. This issue is to:

- Properly identify the root underlying issue causing the modal not to close
- Fix the issue

### PR DESCRIPTION
**Pull request by rezak-otmani**
Closes #738 

add constructor,

improve `componentWillReceiveProps`

and add the state for the render

#### Changelog

**New**

* `ComposedModal` can close when expected

**Changed**
**Removed**

### CODE REVIEW

File: src/components/PaginationV2/PaginationV2.js [hunk 1]
```diff
@@ -186,7 +185,7 @@ export default class PaginationV2 extends Component {
                 )}
           </span>
         </div>
-        <div className="bx--pagination__right bx--pagination--inline">
+        <div className="bx--pagination__right">
```
Comment (joshblack) [inline src/components/PaginationV2/PaginationV2.js]: Is the `bx--pagination--inline` class not needed anymore in this component?

**Comment by joshblack** [comment]
cc @carbon-design-system/ui for those who have context for this component. I'm unsure about background for `ComposedModal` so wanted to check before reviewing.

File: src/components/PaginationV2/PaginationV2.js (hunk 1 above)
Comment (rezak-otmani) [reply src/components/PaginationV2/PaginationV2.js]: it's just that there is a slight shift of the number in using it, it's not centred, but it can be used

Comment (rezak-otmani) [reply src/components/PaginationV2/PaginationV2.js]: yes, I can change this

**Comment by asudoh** [comment]
The history of the commits tells that @tw15egan may have more insights on this, but here's my finding:

* The open/close UI state is controlled by [`is-visible` CSS class](https://github.com/rezak-otmani/carbon-components-react/blob/3cb99f2393a8c5f7df36413a2036c73dd4e9cd27/src/components/ComposedModal/ComposedModal.js#L64)
* The are two sources for open/close state - [`prop.open`](https://github.com/rezak-otmani/carbon-components-react/blob/3cb99f2393a8c5f7df36413a2036c73dd4e9cd27/src/components/ComposedModal/ComposedModal.js#L56) in addition to [`state.open`](https://github.com/rezak-otmani/carbon-components-react/blob/3cb99f2393a8c5f7df36413a2036c73dd4e9cd27/src/components/ComposedModal/ComposedModal.js#L19). Would require `cWRP` to keep them in sync.

@rezak-otmani Do you want to work on changing this PR to put these into cosideration? Thanks!

**Comment by rezak-otmani** [comment]
Hi @asudoh  thanks for your finding
yes I will work to change this PR

File: src/components/ComposedModal/ComposedModal.js [hunk 2]
```diff
@@ -15,9 +15,12 @@ export default class ComposedModal extends Component {
     onKeyDown: PropTypes.func,
   };
 
-  state = {
-    open: this.props.open,
-  };
+  constructor(props) {
```
Comment (joshblack) [inline src/components/ComposedModal/ComposedModal.js]: Could we keep this block the same?

Comment (rezak-otmani) [reply src/components/ComposedModal/ComposedModal.js]: yes I will hand over the block
