### PR TITLE
fix(NumberInput): add button type and disabled

### LINKED ISSUE #358: NumberInput event bubbles up from arrows
## Detailed description

Clicking on the arrows (either up or down) will emit an event that bubbles all the way up to the form wrapper and submits it. This happens even when NumberInput is disabled. Typing numbers into the form doesn't do this.

> Is this issue related to a specific component?
NumberInput

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
7.x.x

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
API Connect, need to ship with carbon components instead of Bluemix components

## Steps to reproduce the issue

1. Place the NumberInput component inside of a Form Component
2. Click on the up or down arrows inside of NumberInput
3. Form will submit

### PR DESCRIPTION
**Pull request by eddiemonge**
- Add button type to arrow button to prevent a form from being submitted
when it is clicked

- Disable the arrow buttons when the NumberInput is disabled just in
case

Fixes #358

### CODE REVIEW

File: src/components/NumberInput/NumberInput-test.js [hunk 1]
```diff
@@ -153,8 +153,13 @@ describe('NumberInput', () => {
       );
 
       const input = wrapper.find('input');
-      const upArrow = wrapper.find('.up-icon');
-      const downArrow = wrapper.find('.down-icon');
+      const upArrow = wrapper.find('.up-icon').parent();
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput-test.js]: target the element that has the actual event handler

File: src/components/NumberInput/NumberInput-test.js [hunk 2]
```diff
@@ -187,8 +192,8 @@ describe('NumberInput', () => {
       );
 
       const input = wrapper.find('input');
-      const upArrow = wrapper.find('.up-icon').last();
-      const downArrow = wrapper.find('.down-icon').last();
+      const upArrow = wrapper.find('Icon.up-icon').closest('button');
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput-test.js]: this would use parent as well but there is a bug in enzyme with mount that I opened

File: src/components/NumberInput/NumberInput.js [hunk 3]
```diff
@@ -105,6 +105,24 @@ export default class NumberInput extends Component {
       value: this.state.value,
     };
 
+    const buttonProps = {
+      type: 'button',
+      className: 'bx--number__control-btn',
+      disabled
+    };
+
+    const createButton = dir => (
```
Comment (eddiemonge) [inline src/components/NumberInput/NumberInput.js]: refactored this so its dry'er

Comment (joshblack) [reply src/components/NumberInput/NumberInput.js]: Do we need to do this if it's only at two call sites?

Comment (eddiemonge) [reply src/components/NumberInput/NumberInput.js]: 1 < 2 so id say yes

Comment (joshblack) [reply src/components/NumberInput/NumberInput.js]: I'm less concerned about file size and more concerned about closure allocs. I'm definitely down if the change made things much easier, but since it's so few call sites the change seems unnecessary.

**Comment by tw15egan** [comment]
Can we also bump the version of `carbon-components` to `8.1.11`? That way the `disabled` styles are bundled in. Otherwise, looks good 👍 ✅

**Comment by eddiemonge** [comment]
the peer is set to `"carbon-components": "^8.0.0",` which would update to that version. updated
