### PR TITLE
fix(OverflowMenu): reposition menu upon change in open state

### LINKED ISSUE #433: Overflow menu position misaligned when scrolling down on page
When scrolled partway down on the page, the overflow menu doesn't open in the expected position. Alignment is fine if the page has not been scrolled down, see attachment. This appears on Firefox and Chrome, using carbon-components-react v5.1.5. Looks like issue #190 proposes a fix for this.

[movingdropdownlist (2).zip](https://github.com/carbon-design-system/carbon-components-react/files/1598162/movingdropdownlist.2.zip)

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #433.

#### Changelog

**New**

Code to recalculate the position of the trigger button, upon opening overflow menu.

### CODE REVIEW

File: src/components/OverflowMenu/OverflowMenu-test.js [hunk 1]
```diff
@@ -3,6 +3,10 @@ import OverflowMenu from '../OverflowMenu';
 import Icon from '../Icon';
 import { shallow, mount } from 'enzyme';
 
+window.requestAnimationFrame = cb => {
```
Comment (joshblack) [inline src/components/OverflowMenu/OverflowMenu-test.js]: Does this line not work for rAF? https://github.com/carbon-design-system/carbon-components-react/blob/master/config/polyfills.js#L20

Comment (asudoh) [reply src/components/OverflowMenu/OverflowMenu-test.js]: Oh didn’t notice we have had the same thing already! Thanks @joshblack for pointing it out!
